### ISSUE TITLE
Unable to create a record with a provided PK

### ISSUE THREAD

**Issue by ardoramor** [LitePalFramework/LitePal#137]
Is there a way to provide a PK (`id`) to a new model? I do not want it to be autoincremented.

This basically follows up on https://github.com/LitePalFramework/LitePal/issues/136. I'm working with widget configuration and want to do something like this:

```
WidgetRecord wr = new WidgetRecord();
wr.setId(appWidgetId);
wr.setSound(sr);
```

However, no matter what I use for `setId()`, the value is ignored and an autoincremented id is used instead of the one specified. In SQL, if I remember correctly, autoincrement is used only if the field was not provided. Can you please clarify? Thanks!

**Comment by guolindev** [comment]
Because LitePal use id as primary key and the entire mechanism is based on that. id must be unique so LitePal can't trust the value that passed in. May be you can guarantee that you won't pass in duplicated value but someone else can't. And with a good programming manner, id should be off of logic, you shouldn't care about the value of it. Once you should, you may need to check about if there's a better way to accomplish that.
