### ISSUE TITLE
LitePal with proguard

### ISSUE THREAD

**Issue by reversecoder** [LitePalFramework/LitePal#362]
Hello,

Firstly thanks for the library.

LitePal suggest to use minifyEnabled(false) with proguard in release version. But I want to use LitePal with minfyEnabled(true) and shrinkResources(true) while using proguard in release version.

I have tried like above I described. But due to minifyEnable(true) always getting column not or class not found exception.

After some debugging I found that the error is occurring at the line where **where** executes-

`String name = "English";`
`List<Language> savedLanguage = DataSupport.where("languageName = ?", name).find(Language.class);`

I am really surprised that if minifyEnable(false) there is no error. But if minifyEnable(true) then getting this crash-

> Caused by: android.database.sqlite.SQLiteException: no such table: l (code 1): , while compiling: SELECT * FROM l WHERE languageName = ?

_**I used proguard.pro like as described in your readme section.**_

Thanks for any workaround.

**Comment by guolindev** [comment]
Obviously, your model class get obscured after you use minifyEnabled. I post the proguard configuration in the readme documents and tested for couple of projects. It should be work.

And if  you still got this error after you use the proguard configuration, I guess it might be something wrong with your proguard-rules.pro file, maybe putting in the wrong place. I can't locate that since I didn't see your project. And if I guess right, it doesn't work for LitePal, it doesn't work for other libraries either. Maybe that's the direction you should get into.

**Comment by priyanka9879** [comment]
if minifyEnable(false)  I am still getting this error in MY LG Phone but on another device its working fine
