### ISSUE TITLE
The object of the parent is not saved

### ISSUE THREAD

**Issue by mosione70** [LitePalFramework/LitePal#466]
I want to use another model in one of my models
But when saving an object from the parent model, the child model is not saved or, if the child model is saved, inside the null parent's field ...

Even when using the sample code, there is no referrals for the parent or child class!

Album album = new Album();
album.setName("album");
album.setPrice(10.99f);
album.setCover(getCoverImageBytes());
album.save();
Song song1 = new Song();
song1.setName("song1");
song1.setDuration(320);
song1.setAlbum(album);    // null saved
song1.save();
Song song2 = new Song();
song2.setName("song2");
song2.setDuration(356);
song2.setAlbum(album);   // null saved
song2.save();

please guide me.

**Comment by mosione70** [comment]
![image](https://user-images.githubusercontent.com/25244666/48585123-ea20d880-e940-11e8-8024-d02ef62a855d.png)

**Comment by guolindev** [comment]
The sample code works fine on my machine and all test cases must pass before I release a version. So I can't see why you have this problem. Maybe paste your snippet may help me find out why.

I will close this issue first because it past for too long. If you still have the problem, please reopen it.
