### ISSUE TITLE
Primitive fields can‘t change to 0 or false

### ISSUE THREAD

**Issue by fzn0268** [LitePalFramework/LitePal#53]
Because of method "isFieldWithDefaultValue" just compares values between the set and the default values by reflection, fields of primitive types such as int, long, float, double, boolean... can't be updated to 0, 0.0, false. However defaultValue annotation mattering when creating table doesn't help either.

**Comment by sinyu890807** [comment]
Well. This is because when you create an instance of Model to update, all fields are assigned with default value. You must not want to see every field set back to default value in database when you just update one field. So the solution is to use setToDefault() method when you want to change field into 0 or false or something.
